### ISSUE TITLE
Support filter-pool argument

### ISSUE THREAD

**Issue by wolf31o2** [blinklabs-io/adder#104]
Let's support a filter-pool argument which should filter to:

- [x] Blocks issued by the pool
- [x] Delegation transactions to the pool
- [x] Pool registration changes

**Comment by ccgarant** [comment]
This would be awesome especially for a screen and audio tracking a pool for blocks won, delegation, and maybe even big stake increases within the wallet, perhaps event pool certificate changes.

**Comment by wolf31o2** [comment]
Currently, blocks won, delegation (in), and pool changes can be tracked easily. For wallet, you would need to track the stake of every single wallet, which would also need rewards calculations. We're not quite there, yet.

**Comment by wolf31o2** [comment]
Blocks: #112 
Delegation: #209 
Registration: #210
