### ISSUE TITLE
Handling some Txs' CBOR fails

### ISSUE THREAD

**Issue by Javieracost** [blinklabs-io/adder#246]
On a few transactions, adder is not emitting the corresponding event.
This translates into errors like this:
`error: eventError":"json: error calling MarshalJSON for type *cbor.LazyValue: unknown data type ([]uint8) for value: <omitted>` being logged and empty messages being sent to webhooks.

Some tx hashes where this happens:
- `54c3502748fec9c14a3dceafc77e2fcf8b9e55b2b57392c21e94ff746df22817`
- `77cd700ff34a3f0a2bcacb03c419ed6315eb4a67d326d6ab9ca92724b3eae647`
- `1bb4608f3e4dc27b2295008716ced37a73f032e2e73087cd35684aa76267c5d5`

**Comment by agaffney** [comment]
This will be fixed by https://github.com/blinklabs-io/gouroboros/pull/714

**Comment by agaffney** [comment]
This is fixed in the v0.23.4 release
